  name: Push the Docker image to AWS ECR Repo
  on:
    workflow_dispatch: 
    #push:
    #  branches:
    #    - main
  permissions:
    id-token: write  
    contents: read 
  jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            aws-region: ${{ vars.AWS_REGION }}
            #aws-region: "us-east-1" 

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Get commit hash
          id: get-commit-hash
          run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
        - name: Get timestamp
          id: get-timestamp
          run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

        - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: "docker-image-repo"
            IMAGE_TAG: "latest"
          run: |
            docker build -t $ECR_REGISTRY/docker-image-repo:$IMAGE_TAG .
            docker push $ECR_REGISTRY/docker-image-repo:$IMAGE_TAG
