name: "Terraform Plan & Apply ### DEV"
on:
  #workflow_dispatch: 
  push:
    branches:
      - dev
permissions:
    id-token: write  
    contents: read  
jobs:
  terraform-plan:
    #environment: dev
    #environment: ${{ github.ref_name }}
    environment: ${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dev-main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.ROLE }}
          aws-region: ${{ vars.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate  

      - name: Terraform Plan
        id: plan
        run: terraform plan  
        env:
          TF_VAR_env: ${{ vars.ENV }}
          TF_VAR_region: ${{ vars.REGION }} 
  terraform-apply:
    #environment: dev
    #environment: ${{ github.ref_name }}
    environment: ${{ github.head_ref || github.ref_name }}
    needs: terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash  
        working-directory: ./dev-main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.ROLE }}
          aws-region: ${{ vars.REGION }}
          #aws-region: "us-east-1" 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 

      - name: Terraform Apply
        env:
          TF_VAR_env:                ${{ vars.ENV }}
          TF_VAR_region:             ${{ vars.REGION }}
          TF_VAR_ecr_app_code_image: ${{ vars.REPO_NAME }}
        run: | 
            terraform init
            terraform plan
            terraform apply -auto-approve
